import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { formatSeconds } from "@/lib/paceEngine";
import type { ResolvedPaceSet } from "@/lib/generatePractice";

export default async function PracticeDetailPage({
  params,
}: PageProps<"/practices/[practiceId]">) {
  const { practiceId } = await params;

  const practice = await prisma.practice.findUnique({
    where: { id: practiceId },
    include: { group: true },
  });
  if (!practice) notFound();

  const paceSets: ResolvedPaceSet[] = practice.intervals ? JSON.parse(practice.intervals) : [];

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-semibold">
            {practice.group.name} — {practice.focus}
          </h1>
          <p className="text-slate-500 text-sm mt-1">
            {new Date(practice.createdAt).toLocaleString()} · generated by {practice.source}
          </p>
        </div>
        <Link href={`/groups/${practice.groupId}`} className="text-sm text-slate-600 hover:text-slate-900">
          ← Back to group
        </Link>
      </div>

      <section className="rounded-lg border border-slate-200 bg-white p-5">
        <pre className="text-sm whitespace-pre-wrap font-mono text-slate-800">{practice.content}</pre>
      </section>

      {paceSets.length > 0 && (
        <section className="flex flex-col gap-4">
          <h2 className="font-medium text-slate-700">Individual pace breakdown</h2>
          {paceSets.map((set, i) => (
            <div key={i} className="rounded-lg border border-slate-200 bg-white p-5">
              <h3 className="font-medium text-sm">{set.label}</h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Reps scaled per group so the set takes about the same total time for everyone.
              </p>
              <div className="mt-3 overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-slate-500 border-b border-slate-200">
                      <th className="py-1 pr-4">Swimmer</th>
                      <th className="py-1 pr-4">Group</th>
                      <th className="py-1 pr-4">Reps</th>
                      <th className="py-1 pr-4">Target</th>
                      <th className="py-1 pr-4">Interval</th>
                    </tr>
                  </thead>
                  <tbody>
                    {set.intervals
                      .slice()
                      .sort((a, b) => a.group.localeCompare(b.group) || a.targetTime - b.targetTime)
                      .map((iv) => (
                        <tr key={iv.swimmerId} className="border-b border-slate-100 last:border-0">
                          <td className="py-1 pr-4">{iv.swimmerName}</td>
                          <td className="py-1 pr-4">
                            <span
                              className={`text-xs font-medium rounded px-1.5 py-0.5 ${
                                iv.group === "A"
                                  ? "bg-emerald-100 text-emerald-700"
                                  : iv.group === "B"
                                    ? "bg-amber-100 text-amber-700"
                                    : "bg-slate-100 text-slate-600"
                              }`}
                            >
                              {iv.group}
                            </span>
                          </td>
                          <td className="py-1 pr-4 text-slate-600">{set.groupReps[iv.group]}x</td>
                          <td className="py-1 pr-4 text-slate-600">{formatSeconds(iv.targetTime)}</td>
                          <td className="py-1 pr-4 text-slate-600">on {formatSeconds(iv.interval)}</td>
                        </tr>
                      ))}
                    {set.intervals.length === 0 && (
                      <tr>
                        <td colSpan={5} className="py-2 text-slate-500">
                          No swimmer times on file for this set.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          ))}
        </section>
      )}
    </div>
  );
}
